#!/bin/bash
set -e

exec 2> >(grep -vE "^dig: couldn't get address for 'ns.iserv.eu': failure$")

run_regdns()
{
  if [ -x "$(which regdns)" ]
  then
    regdns "$@"
  else
    ssh "$(hostname -d)" regdns "$@"
  fi
}

DEFIF="$(. /usr/lib/iserv/ipv6_defif)"

[ -z "$DEFIF" ] && exit 0

IPs="$(netquery6 -i "$DEFIF" -g "ip" | while read i
do
  [ -z "$i" ] && continue
  perl -e 'use Net::IP; print Net::IP::ip_expand_address "'$i'", 6;'
  echo
done | sort)"
  
CURIPs="$(dig +short "$(hostname)" AAAA @ns.iserv.eu | while read i
do
  [ -z "$i" ] && continue
  [ "$i" = ";; connection timed out; no servers could be reached" ] && continue
  perl -e 'use Net::IP; print Net::IP::ip_expand_address "'$i'", 6;'
  echo
done | sort)"

if ! [ -z "$IPs" ] && ! [ "$IPs" = "$CURIPs" ]
then
  run_regdns -d "$(hostname). AAAA"
  for i in ${IPs[@]}
  do
    run_regdns -a "$(hostname). 300 AAAA $i"
  done
fi
